// The editor's TipTap extension set.
//
// This MUST stay in step with backend/src/blog/schema/extensions.ts — the
// backend renders the stored HTML from the same schema, so a node configured
// differently here produces markup the reader never sees, or vice versa. The
// shared node/mark allowlist lives in ./nodes.ts, which is generated by
// `npm run sync:blog-schema` in the backend.
//
// The one intentional difference: this file attaches a React node view to the
// figure so it is editable in the admin. The rendered HTML is identical.

import { Node, mergeAttributes } from "@tiptap/core";
import { ReactNodeViewRenderer } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import { Table, TableCell, TableHeader, TableRow } from "@tiptap/extension-table";
import { FIGURE_ALIGNMENTS, HEADING_LEVELS, type FigureAlignment } from "./nodes";
import { FigureView } from "@/components/admin/blog/FigureView";

export const Figure = Node.create({
  name: "figure",
  group: "block",
  // The caption is inline content held by the figure itself — see the note in
  // the backend's extensions.ts for why this is not a separate figcaption node.
  content: "inline*",
  draggable: true,
  atom: false,
  isolating: true,

  addAttributes() {
    return {
      src: { default: null },
      alt: { default: "" },
      width: { default: null },
      height: { default: null },
      align: {
        default: "center" as FigureAlignment,
        parseHTML: (el: HTMLElement) => {
          const v = el.getAttribute("data-align") as FigureAlignment | null;
          return v && FIGURE_ALIGNMENTS.includes(v) ? v : "center";
        },
      },
      href: { default: null },
    };
  },

  parseHTML: () => [{ tag: "figure" }],

  renderHTML({ HTMLAttributes }) {
    const { src, alt, width, height, align, href } = HTMLAttributes as Record<string, unknown>;

    const img = [
      "img",
      {
        src: src as string,
        alt: (alt as string) ?? "",
        ...(width ? { width: String(width) } : {}),
        ...(height ? { height: String(height) } : {}),
        loading: "lazy",
        decoding: "async",
      },
    ];

    const inner = href
      ? ["a", { href: href as string, target: "_blank", rel: "noopener noreferrer" }, img]
      : img;

    return ["figure", mergeAttributes({ "data-align": (align as string) ?? "center" }), inner, ["figcaption", 0]];
  },

  // The editing surface. Rendering (renderHTML above) is unaffected.
  addNodeView() {
    return ReactNodeViewRenderer(FigureView);
  },
});

/** Fresh array per call — TipTap mutates extension instances on mount. */
export function blogExtensions() {
  return [
    StarterKit.configure({
      heading: { levels: [...HEADING_LEVELS] },
      link: {
        openOnClick: false,
        autolink: true,
        protocols: ["http", "https", "mailto"],
        HTMLAttributes: { rel: "noopener noreferrer", target: "_blank" },
      },
    }),
    Table.configure({ resizable: true }),
    TableRow,
    TableHeader,
    TableCell,
    Figure,
  ];
}
